# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Protocal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=32)),
                ('TypeDesc', models.CharField(max_length=128)),
                ('TypeDefinition', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'T_DataType',
            },
        ),
        migrations.AlterField(
            model_name='quotation',
            name='AttributeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Protocal.DataType'),
        ),
    ]
